server:
  port: 8082

spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness-activity
      database: fitness-activity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    activity.queue
  routing:
    activity.tracking


