server:
  port: 8083

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness-activity
      database: fitness-activity

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
