spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_user_db
    username: root
    password: Salman@121
  jpa:
    hibernate:
      ddl-auto: update
